### ISSUE TITLE
Attaching a screenshot when a test fails

### ISSUE THREAD

**Issue by rodney-wilson** [reportportal/agent-js-mocha#11]
Is there any way to attach a screenshot when a test fails?

**Comment by ElenaRomanchuk** [comment]
This reporter doesn't take screenshot automatically when test fails. However, you can attach an image to the test using additional API: https://github.com/reportportal/agent-js-mocha/tree/develop#report-logs-and-attachments. So, if your framework provides possibility to save screenshots with specified filename, this feature can help you.
Example of how to report attachments you can find here: https://github.com/reportportal/examples-js/blob/master/example-mocha/spec/logTest.spec.js

**Comment by ElenaRomanchuk** [comment]
@rodney-wilson Please, let us know if it solves your problem.

**Comment by rodney-wilson** [comment]
@ElenaRomanchuk thank you for the info!
