### ISSUE TITLE
Error: invalid reporter "./lib/mocha-rp-reporter.js"

### ISSUE THREAD

**Issue by ashlynjiang** [reportportal/agent-js-mocha#12]
hi,

I got Error: invalid reporter "./lib/mocha-rp-reporter.js" error while running `npm test`

**Comment by Hussain-Ruhullah** [comment]
any updates ?

**Comment by jhendershott** [comment]
One thing that may be causing this issue is the npm package is rp-mocha-reporter but the example is mocha-rp-reporter which is a different library.

**Comment by ElenaRomanchuk** [comment]
Hi @Hussain-Ruhullah, @ashlynjiang, @jhendershott ,
@jhendershott was right, the readme file wasn't consistent, so example was wrong.
We have just released the new version of mocha reporter as a new package `@reportportal/agent-js-mocha`: https://www.npmjs.com/package/@reportportal/agent-js-mocha.
It's fully compatible with ReportPortal version 5.* and async API v2 and has some additional features.
The package `rp-mocha-reporter` is deprecated now.
Readme is up to date now.
I recommend you to try it. Hope you will like it.
