### ISSUE TITLE
Is this project working?

### ISSUE THREAD

**Issue by bhoppeadoy** [reportportal/agent-js-mocha#37]
I was trying to use this with my mocha protractor/selenium tests. I installed rp-mocha-reporter v2.0.7

Issue #1 
In the README, under the reporterOptions, the wrong report is specified:
  reporter: 'mocha-rp-reporter',
should this be?
  reporter: 'rp-mocha-reporter',

Issue #2, 
Using reporter 'rp-mocha-reporter', I was able to connect to my portal, but when using this from the README:
  const PublicReportingAPI = require('agent-js-mocha/lib/publicReportingAPI');

I get an error that Cannot find module 'agent-js-mocha/lib/publicReportingAPI'

So looks like the README and source code do not match up. Is this at a stable point yet?

**Comment by evjlobanova** [comment]
@bhoppeadoy JS agent has been written by external contributor. And it was not supported before.

Now we are updating and re-writing the agent and client.
API v2 isn't supported in 1.0.12 version of mocha-rp-reporter. New version with v2 support hasn't been released yet. It will be released in 2 weeks as @reportportal/agent-js-mocha package. mocha-rp-reporter will be deprecated.

As for now, you can use the version in the dev branch.
@ElenaRomanchuk Elena can answer on your questions if you have any.

**Comment by ElenaRomanchuk** [comment]
Hi @bhoppeadoy,
We have just released the new version of mocha reporter: https://www.npmjs.com/package/@reportportal/agent-js-mocha.
It's fully compatible with ReportPortal version 5.* and async API v2. I recommend you to try it. Hope this solves your problem :)
