### ISSUE TITLE
setTestCaseId for suite not displayed in UI 

### ISSUE THREAD

**Issue by TAVkiev** [reportportal/agent-js-mocha#43]
Hay
According to this doc, setTestCaseId - Set test case id to the current test/suite. I put setTestCaseId to before hook, as in example.  I don't see this suite id in report portal UI. Works with test case id, when I put it to 'it' section and I can see this id within 'edit' modal for the test. But I can't see suite ID within 'edit' modal for suite, or it is displaying somewhere in another place ?

**Comment by AmsterGet** [comment]
Hi @TAVkiev !
The test case ID for such items is set correctly, but is hidden in UI.
You can always get information about the testCaseId property or others using the API or simply in the browser developer tools.
Feel free to reopen this issue in case of other questions related to the topic.
