### ISSUE TITLE
not able to integrate mocha (typescript test)

### ISSUE THREAD

**Issue by tokarthik** [reportportal/agent-js-mocha#45]
I have a mocha unit test written on the typescript.

Example 

In the package.json we have script ` "test": "mocha 'tests/**/*.test.ts'"`

another ci script ` "ci:test": "RUNTIME_ENV=Test TS_NODE_TRANSPILE_ONLY=true JUNIT_REPORT_PATH=./reports/tests.xml mocha 'tests/**/*.test.ts' --reporter mocha-jenkins-reporter",` 

Tried `npm test or npm ci` both are not working 
I have followed the example  https://github.com/reportportal/examples-js/tree/master/example-mocha

1. I have tried to run the main.js in the script file ` "test": "mocha 'tests/main.js'"` 
2. ci script ` "ci:test": "RUNTIME_ENV=Test TS_NODE_TRANSPILE_ONLY=true JUNIT_REPORT_PATH=./reports/tests.xml mocha 'tests/**/*.test.ts' --reporter reportportal/agent-js-mocha",` 
Both didn't worked , Is there anything I am missing ?  

Find my folder structure where my unit test is kept. 
![image](https://user-images.githubusercontent.com/3865402/93223988-8cda5600-f768-11ea-83c2-e8564080e720.png)

**Comment by tokarthik** [comment]
@AmsterGet could you please guide me regarding the above issue.

**Comment by AmsterGet** [comment]
Hi @tokarthik !
Could you please provide any logs if they exist?

**Comment by tokarthik** [comment]
@AmsterGet thanks for your reply i have attached the log 
`
PS C:\Users\karthikeyans1\workspace\checkout> npm install --loglevel verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--loglevel',
npm verb cli   'verbose'
npm verb cli ]
npm info using npm@6.14.5
npm info using node@v12.18.2
npm verb npm-session 89d63bdf153ede06
npm info lifecycle checkout@1.0.0~preinstall: checkout@1.0.0
npm timing stage:loadCurrentTree Completed in 3935ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 31ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1910ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2419ms
npm timing stage:loadIdealTree Completed in 4978ms
npm timing stage:generateActionsToTake Completed in 157ms
npm verb correctMkdir C:\Users\karthikeyans1\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\karthikeyans1\AppData\Roaming\npm-cache\_locks\staging-78debc2c33b6ca41.lock for C:\Users\karthikeyans1\workspace\checkout\node_modules\.staging
npm verb unlock done using C:\Users\karthikeyans1\AppData\Roaming\npm-cache\_locks\staging-78debc2c33b6ca41.lock for C:\Users\karthikeyans1\workspace\checkout\node_modules\.staging
npm timing stage:executeActions Completed in 26ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm info linkStuff checkout@1.0.0
npm info lifecycle checkout@1.0.0~install: checkout@1.0.0
npm info lifecycle checkout@1.0.0~postinstall: checkout@1.0.0
npm info lifecycle checkout@1.0.0~prepublish: checkout@1.0.0
npm info lifecycle checkout@1.0.0~prepare: checkout@1.0.0
npm timing stage:runTopLevelLifecycles Completed in 9732ms
npm verb saving []
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN checkout@1.0.0 No repository field.
npm WARN The package @reportportal/agent-js-mocha is included as both a dev and production dependency.

npm timing audit submit Completed in 1583ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1584ms
npm timing audit body Completed in 2ms
audited 1414 packages in 11.213s

30 packages are looking for funding
  run `npm fund` for details

found 9 vulnerabilities (7 low, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
npm verb exit [ 0, true ]
npm timing npm Completed in 13067ms
npm info ok`


`npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'test',
npm verb cli   '--loglevel',
npm verb cli   'verbose'
npm verb cli ]
npm info using npm@6.14.5
npm info using node@v12.18.2
npm verb run-script [ 'pretest', 'test', 'posttest' ]
npm info lifecycle checkout@1.0.0~pretest: checkout@1.0.0
npm info lifecycle checkout@1.0.0~test: checkout@1.0.0

> checkout@1.0.0 test C:\Users\karthikeyans1\workspace\checkout
> mocha 'tests/**/*.test.ts'


npm verb lifecycle checkout@1.0.0~test: unsafe-perm in lifecycle true
npm verb lifecycle checkout@1.0.0~test: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\karthikeyans1\workspace\checkout\nod
e_modules\.bin;C:\Users\karthikeyans1\bin;C:\Users\karthikeyans1\AppData\Local\Programs\Git\mingw64\bin;C:\Users\karthikeyans1\AppData\Local\Programs\Git\usr\local\bin;C:\U
sers\karthikeyans1\AppData\Local\Programs\Git\usr\bin;C:\Users\karthikeyans1\AppData\Local\Programs\Git\usr\bin;C:\Users\karthikeyans1\AppData\Local\Programs\Git\mingw64\bi
n;C:\Users\karthikeyans1\AppData\Local\Programs\Git\usr\bin;C:\Users\karthikeyans1\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\windows-amd
64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Docker\Docker\resources\b
in;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Kubernetes\Minikube;C:\Program Files\nodejs;C:\Program Files (x86)\Brackets\command;C:\Users\karthikeyans1\AppD
ata\Local\Microsoft\WindowsApps;C:\Users\karthikeyans1\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\karthikeyans1\AppData\Local\atom\bin;C:\Users\karthikeyans1\App
Data\Local\Programs\Git\cmd;C:\Users\karthikeyans1\AppData\Local\Programs\Git\mingw64\bin;C:\Users\karthikeyans1\AppData\Local\Programs\Git\usr\bin;C:\Users\karthikeyans1\A
ppData\Roaming\npm;C:\Users\karthikeyans1\AppData\Local\Programs\Git\usr\bin\vendor_perl;C:\Users\karthikeyans1\AppData\Local\Programs\Git\usr\bin\core_perl
npm verb lifecycle checkout@1.0.0~test: CWD: C:\Users\karthikeyans1\workspace\checkout
npm info lifecycle checkout@1.0.0~test: Failed to exec test script
npm ERR! Test failed.  See above for more details.
npm verb exit [ 1, true ]
npm timing npm Completed in 32731ms
npm verb code 1


`

**Comment by tokarthik** [comment]
added .mocharc.yml file 
and executed the test using  `mocha 'tests/**/*.test.ts`
`require:
    - ts-node/register
    - tsconfig-paths/register
    - source-map-support/register
timeout: 60000
reporter: '@reportportal/agent-js-mocha'
reporter-options:
    - 'endpoint=reportportal url'
    - 'token=rptoken'
    - 'launch=unittest'
    - 'project=superadmin_personal'
    - 'description=LAUNCH_DESCRIPTION'
exit: true
`
