### ISSUE TITLE
skippedIssue ReporterOption not resolving string

### ISSUE THREAD

**Issue by Connerj55** [reportportal/agent-js-mocha#46]
In mochaReporter.js,  _this.options.reporterOptions.skippedIssue_ is being set as a string from my .mocharc.yaml.   This options needs to be cast to a boolean for the following logic:
`this.options.reporterOptions.skippedIssue === false `

.mocharc.yaml:
```
---
reporter-option:
  - token=removed
  - endpoint=removed
  - project=mhc_projects 
  - username=mhc_tester
  - launch=testlaunchname
  - skippedIssue=false
```

Resolution: Cast the skippedIssue option to a boolean before pushing it onto the systemAttributes.

**Comment by Connerj55** [comment]
https://github.com/reportportal/agent-js-mocha/pull/47

**Comment by AmsterGet** [comment]
Closed [here](https://github.com/reportportal/agent-js-mocha/pull/47)
