### ISSUE TITLE
rerun option not work

### ISSUE THREAD

**Issue by TAVkiev** [reportportal/agent-js-mocha#54]
Hi all, faced with problem related to rerun functionality. I am using config:
	rerunOf: id,
	rerun: true,
	
I red doc here: https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/rerun.md	
Expected that new results will override previous one in the same launch for the same tests. Instead new results added to previous - in the end I received duplicates. "rerun" label is added for launch, but not for test items.

OS: WIndows 10
Nodejs: 14.16.0
Report portal: 5.3.5 (https://reportportal.epam.com/)

Actually I am received few results, but both created duplicates:

1.  I send one test for pass and one for fail, then repeat run for the same launch, but send all the same tests for pass. Result, duplicates items:

![second_case](https://user-images.githubusercontent.com/18603511/116108305-7744eb80-a6bc-11eb-89a5-9cab874fc22c.PNG)

**Comment by AmsterGet** [comment]
Hello @TAVkiev !
There is a known issue with RP backend side v5.3.5 (please refer https://github.com/reportportal/reportportal/issues/1362, https://github.com/reportportal/reportportal/issues/1358, https://github.com/reportportal/reportportal/issues/1317, https://github.com/reportportal/reportportal/issues/1327).

**Comment by AmsterGet** [comment]
Closed as a duplicate.
